export const PLACES_DATA_LOADED = "PLACES_DATA_LOADED";
export const MENU_DATA_LOADED = "MENU_DATA_LOADED";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const ORDER_PLACED = "ORDER_PLACED";
export const ORDER_STATUS_CHECKED = "ORDER_STATUS_CHECKED";
export const API_ERROR = "API_ERROR";