export const ORDER_STATUS_NONE = "ORDER_STATUS_NONE";
export const ORDER_STATUS_ORDERED = "ORDER_STATUS_ORDERED";
export const ORDER_STATUS_ACCEPTED = "ORDER_STATUS_ACCEPTED";
export const ORDER_STATUS_IN_PROGRESS = "ORDER_STATUS_IN_PROGRESS";
export const ORDER_STATUS_READY = "ORDER_STATUS_READY";
export const ORDER_STATUS_FINISHED = "ORDER_STATUS_FINISHED";
