export const API_BASE = process.env.PUBLIC_URL + "/json"; //TODO http
// export const API_PLACES = API_BASE + "/places";
export const API_PLACES = API_BASE + "/places.json";
// export const API_MENU = API_BASE + "/menu/{placeId}";
export const API_MENU = API_BASE + "/menu.json";
// export const CREATE_ORDER = API_BASE + "/create-order";
export const CREATE_ORDER = API_BASE + "/paymentRequest.json";
// export const API_MENU = API_BASE + "/order-status/{orderId}";
export const ORDER_STATUS = API_BASE + "/orderStatus.json";